/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  MaxLength,
  IsOptional,
  ValidateNested,
  IsDate,
  IsEnum,
} from "class-validator";
import { GenerationLogUpdateManyWithoutPackageModelsInput } from "./GenerationLogUpdateManyWithoutPackageModelsInput";
import { Type } from "class-transformer";
import { EnumPackageModelLastGeneratedStatus } from "./EnumPackageModelLastGeneratedStatus";
import { PackageFileUpdateManyWithoutPackageModelsInput } from "./PackageFileUpdateManyWithoutPackageModelsInput";

@InputType()
class PackageModelUpdateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  displayName?: string | null;

  @ApiProperty({
    required: false,
    type: () => GenerationLogUpdateManyWithoutPackageModelsInput,
  })
  @ValidateNested()
  @Type(() => GenerationLogUpdateManyWithoutPackageModelsInput)
  @IsOptional()
  @Field(() => GenerationLogUpdateManyWithoutPackageModelsInput, {
    nullable: true,
  })
  generationLogs?: GenerationLogUpdateManyWithoutPackageModelsInput;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  lastGeneratedAt?: Date | null;

  @ApiProperty({
    required: false,
    enum: EnumPackageModelLastGeneratedStatus,
  })
  @IsEnum(EnumPackageModelLastGeneratedStatus)
  @IsOptional()
  @Field(() => EnumPackageModelLastGeneratedStatus, {
    nullable: true,
  })
  lastGeneratedStatus?: "Initial" | "Completed" | "Error" | null;

  @ApiProperty({
    required: false,
    type: () => PackageFileUpdateManyWithoutPackageModelsInput,
  })
  @ValidateNested()
  @Type(() => PackageFileUpdateManyWithoutPackageModelsInput)
  @IsOptional()
  @Field(() => PackageFileUpdateManyWithoutPackageModelsInput, {
    nullable: true,
  })
  packageFiles?: PackageFileUpdateManyWithoutPackageModelsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  summary?: string | null;
}

export { PackageModelUpdateInput as PackageModelUpdateInput };
