steps:
  - id: "docker-pull"
    name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args: ["-c", "docker pull $_IMAGE:latest || exit 0"]
    waitFor: ["-"]

  - id: "docker-pull-latest-build"
    name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args: ["-c", "docker pull $_IMAGE:latest-build || exit 0"]
    waitFor: ["-"]

  - id: "docker-pull-app-base"
    name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args: ["-c", "docker pull $_APP_BASE_IMAGE:latest || exit 0"]
    waitFor: ["-"]

  - id: "docker-build-build"
    name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t=$_IMAGE:$SHORT_SHA-build"
      - "-t=$_IMAGE:latest-build"
      - "--target=build"
      - "."
      - --cache-from=$_IMAGE:latest-build
    waitFor: ["docker-pull-latest-build"]

  - id: "docker-build"
    name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t=$_IMAGE:$SHORT_SHA"
      - "-t=$_IMAGE:latest"
      - "."
      - --cache-from=$_IMAGE:$SHORT_SHA-build
      - --cache-from=$_IMAGE:latest
    waitFor: ["docker-pull", "docker-build-build"]

  - id: "docker-build-app-base"
    name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t=$_APP_BASE_IMAGE:$SHORT_SHA"
      - "-t=$_APP_BASE_IMAGE:latest"
      - "."
      - --cache-from=$_APP_BASE_IMAGE:latest
    dir: packages/amplication-data-service-generator
    waitFor: ["docker-pull-app-base"]

  - id: "docker-push-latest-build"
    name: "gcr.io/cloud-builders/docker"
    args: ["push", "$_IMAGE:latest-build"]
    waitFor: ["docker-build-build"]

  - id: "docker-push"
    name: "gcr.io/cloud-builders/docker"
    args: ["push", "$_IMAGE:$SHORT_SHA"]
    waitFor: ["docker-build"]

  - id: "docker-push-latest"
    name: "gcr.io/cloud-builders/docker"
    args: ["push", "$_IMAGE:latest"]
    waitFor: ["docker-push"]

  - id: "docker-push-app-base"
    name: "gcr.io/cloud-builders/docker"
    args: ["push", "$_APP_BASE_IMAGE:$SHORT_SHA"]
    waitFor: ["docker-build-app-base"]

  - id: "docker-push-app-base-latest"
    name: "gcr.io/cloud-builders/docker"
    args: ["push", "$_APP_BASE_IMAGE:latest"]
    waitFor: ["docker-push-app-base"]

  - id: "terraform-init"
    name: "hashicorp/terraform:0.13.4"
    args: ["init"]
    dir: terraform/envs/dev
    waitFor: ["-"]

  - id: "terraform-apply"
    name: "hashicorp/terraform:0.13.4"
    args:
      - "apply"
      - "-auto-approve"
      # 20 minutes
      - "-lock-timeout=1200s"
    dir: terraform/envs/dev
    env:
      - "TF_VAR_image_id=$_IMAGE:$SHORT_SHA"
      - "TF_VAR_generated_app_base_image_id=$_APP_BASE_IMAGE:$SHORT_SHA"
    waitFor: ["terraform-init", "docker-push"]

  - name: "node:12-stretch"
    entrypoint: bash
    args:
      - -c
      - |
        set -e;
        wget -O /workspace/cloud_sql_proxy https://storage.googleapis.com/cloudsql-proxy/v1.16/cloud_sql_proxy.linux.386;
        chmod +x /workspace/cloud_sql_proxy;
        /workspace/cloud_sql_proxy -dir=/workspace -instances=$PROJECT_ID:$_REGION:$_DB_INSTANCE=tcp:5432 & sleep 2
        cd packages/amplication-server/prisma/;
        POSTGRESQL_URL="postgresql://$_POSTGRESQL_USER:$_POSTGRESQL_PASSWORD@localhost:5432/$_POSTGRESQL_DB" npx @prisma/cli migrate up --create-db --auto-approve --experimental;
    waitFor: ["terraform-apply"]
images:
  - $_IMAGE:latest-build
  - $_IMAGE:$SHORT_SHA
  - $_IMAGE:latest
  - $_APP_BASE_IMAGE:$SHORT_SHA
  - $_APP_BASE_IMAGE:latest
# 1 hour
timeout: 3600s
