apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: build-artifacts
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeName: {{ .Values.buildArtifactsPv.name }}
  storageClassName: efs-sc
  volumeMode: Filesystem
