apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.buildArtifactsPv.name }}
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: efs.csi.aws.com
    volumeHandle: {{ .Values.buildArtifactsPv.volumeHandle }}
