apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dsg-jobs
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeName: {{ .Values.dsgJobsPv.name }}
  storageClassName: efs-sc
  volumeMode: Filesystem
