/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface CommitProjectPendingChanges {
  /**
   * the ID of the project
   */
  projectId: string;
  /**
   * a message that describes the changes in the commit. The message can be created based on the pending changes in the project
   */
  commitMessage: string;
}
