/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface CreateModuleEnum {
  /**
   * the ID of the module in which the Enum is created. This is not the module name, but the ID of the module. and will be q unique identifier and not a word like 'customer'. e.g.: 'mod_1234'
   */
  moduleId: string;
  /**
   * the ID of the resource in which the Enum is created. If there are multiple resources available in the context, show the user a list of resources to choose from. If there is no resource available, do not use projectId instead
   */
  resourceId: string;
  /**
   * the name of the enum. e.g.: 'EnumCustomerStatus'
   */
  enumName: string;
  /**
   * the description of the enum. e.g.: 'The status of a customer'
   */
  enumDescription: string;
  /**
   * a list of members of the Enum.
   */
  members: {
    /**
     * the name of the enum member property. e.g.: 'InProgress'
     */
    name: string;
    /**
     * the value of the enum member property. e.g.: 'InProgress'
     */
    value: string;
  }[];
}
