/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface CreateModuleAction {
  /**
   * the ID of the module in which the action is created. The moduleId is different then the serviceID. The moduleId is the ID of the module in which the action is created. The serviceId is the ID of the service in which the module exist. You can use the function get getServiceModules to get a list of available modules in a service.
   */
  moduleId: string;
  /**
   * the ID of the service in which the Action is created. If there are multiple services available in the context, show the user a list of services to choose from. If there is no service available, do not use projectId instead
   */
  serviceId: string;
  /**
   * the name of the action. e.g.: 'Create Customer'
   */
  actionName: string;
  /**
   * the description of the action. e.g.: 'Creates a new customer'
   */
  actionDescription: string;
  /**
   * the GraphQL operation of the action. e.g.: 'mutation'
   */
  gqlOperation: "Query" | "Mutation";
  /**
   * the REST verb of the action. e.g.: 'POST'
   */
  restVerb: "Get" | "Post" | "Put" | "Delete" | "Patch";
  /**
   * the path of the action in REST api, without the controller name. e.g.: '/:id'
   */
  path: string;
  inputType: {
    /**
     * The type of the input. When the type is Dto, the dtoId property is required. You can use the function getModuleDtosAndEnums to get a list of available DTOs in the module or other modules.
     */
    type: "String" | "Boolean" | "Integer" | "Float" | "DateTime" | "Dto";
    /**
     * whether the property is an array or not
     */
    isArray: boolean;
    /**
     * the ID of the DTO. If the type is a DTO .
     */
    dtoId?: string;
  };
  outputType: {
    /**
     * The type of the input. When the type is Dto, the dtoId property is required. You can use the function getModuleDtosAndEnums to get a list of available DTOs in the module or other modules.
     */
    type: "String" | "Boolean" | "Integer" | "Float" | "DateTime" | "Dto";
    /**
     * whether the property is an array or not
     */
    isArray: boolean;
    /**
     * the ID of the DTO. If the type is a DTO .
     */
    dtoId?: string;
  };
  /**
   * the source of the input in the REST API. e.g.: 'Query'
   */
  restInputSource: "Query" | "Params" | "Body" | "Split";
  /**
   * When restInputSource is 'Split', this is the name of the property that will be received in the params part of the URL
   */
  restInputParamsPropertyName?: string;
  /**
   * When restInputSource is 'Split', this is the name of the property that will be received in the body of the request
   */
  restInputBodyPropertyName?: string;
  /**
   * When restInputSource is 'Split', this is the name of the property that will be received in the query part of the URL
   */
  restInputQueryPropertyName?: string;
}
