/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface CreateModuleDto {
  /**
   * the ID of the module in which the DTO is created. The moduleID is different then the serviceID. The moduleID is the ID of the module in which the DTO is created. The serviceID is the ID of the service in which the module exist. You can use the function get getServiceModules to get a list of available modules in a service.
   */
  moduleId: string;
  /**
   * the ID of the service in which the DTO is created. If there are multiple services available in the context, show the user a list of services to choose from. If there is no service available, do not use projectId instead
   */
  serviceId: string;
  /**
   * the name of the dto. e.g.: 'customerCreateInput'
   */
  dtoName: string;
  /**
   * the description of the dto. e.g.: 'the input type for creating a new customer'
   */
  dtoDescription: string;
  /**
   * a list of properties of the DTO.
   */
  properties: {
    /**
     * the name of the property
     */
    name: string;
    /**
     * whether the property is optional or not
     */
    isOptional: boolean;
    /**
     * whether the property is an array or not
     */
    isArray: boolean;
    /**
     * the types of the property
     */
    propertyTypes: {
      /**
       * The type of the property. Use the type DTO for DTOs and Enums. When the type is Dto, the dtoId property is required. You can use the function getModuleDtosAndEnums to get a list of available DTOs and Enums in the module or other modules.
       */
      type:
        | "String"
        | "Boolean"
        | "Integer"
        | "Float"
        | "DateTime"
        | "Dto"
        | "Json";
      /**
       * whether the property is an array or not
       */
      isArray: boolean;
      /**
       * the ID of the DTO. If the type is a DTO or Enum.
       */
      dtoId?: string;
    }[];
  }[];
}
