/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface GetPlugins {
  /**
   * The type of code generator of the resource. When not available, fetch the resource details to find the codeGenerator.
   */
  codeGenerator: "DotNet" | "NodeJs";
}
