/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * THe schedule on which the job will be executed in. unix-cron syntax
 */
export type Schedule = string;
/**
 * The timezone to execute the schedule according to. Defaults to UTC. Should be from the list https://momentjs.com/timezone/.
 */
export type TimeZone = string;
/**
 * The HTTP request method
 */
export type HTTPMethod = "DELETE" | "GET" | "HEAD" | "OPTIONS" | "PATCH" | "POST" | "PUT";
/**
 * The HTTP request URL
 */
export type URL = string;
/**
 * The HTTP request body as string
 */
export type Body = string;

export interface Config {
  schedule: Schedule;
  timezone?: TimeZone;
  request: Request;
  [k: string]: unknown;
}
/**
 * HTTP Request to execute
 */
export interface Request {
  method?: HTTPMethod;
  url: URL;
  body?: Body;
  headers?: HTTPHeaders;
  [k: string]: unknown;
}
/**
 * The HTTP request headers as key-value string pairs
 */
export interface HTTPHeaders {
  [k: string]: string;
}
