/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import * as gqlUserRoles from "../../auth/gqlUserRoles.decorator";
import * as abacUtil from "../../auth/abac.util";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { CreateGitHubRepositoryArgs } from "./CreateGitHubRepositoryArgs";
import { UpdateGitHubRepositoryArgs } from "./UpdateGitHubRepositoryArgs";
import { DeleteGitHubRepositoryArgs } from "./DeleteGitHubRepositoryArgs";
import { GitHubRepositoryFindManyArgs } from "./GitHubRepositoryFindManyArgs";
import { GitHubRepositoryFindUniqueArgs } from "./GitHubRepositoryFindUniqueArgs";
import { GitHubRepository } from "./GitHubRepository";
import { GitHubRepositoryService } from "../gitHubRepository.service";

@graphql.Resolver(() => GitHubRepository)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class GitHubRepositoryResolverBase {
  constructor(
    protected readonly service: GitHubRepositoryService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "GitHubRepository",
    action: "read",
    possession: "any",
  })
  async _gitHubRepositoriesMeta(
    @graphql.Args() args: GitHubRepositoryFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @graphql.Query(() => [GitHubRepository])
  @nestAccessControl.UseRoles({
    resource: "GitHubRepository",
    action: "read",
    possession: "any",
  })
  async gitHubRepositories(
    @graphql.Args() args: GitHubRepositoryFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<GitHubRepository[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "GitHubRepository",
    });
    const results = await this.service.findMany(args);
    return results.map((result) => permission.filter(result));
  }

  @graphql.Query(() => GitHubRepository, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "GitHubRepository",
    action: "read",
    possession: "own",
  })
  async gitHubRepository(
    @graphql.Args() args: GitHubRepositoryFindUniqueArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<GitHubRepository | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "own",
      resource: "GitHubRepository",
    });
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return permission.filter(result);
  }

  @graphql.Mutation(() => GitHubRepository)
  @nestAccessControl.UseRoles({
    resource: "GitHubRepository",
    action: "create",
    possession: "any",
  })
  async createGitHubRepository(
    @graphql.Args() args: CreateGitHubRepositoryArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<GitHubRepository> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "create",
      possession: "any",
      resource: "GitHubRepository",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"GitHubRepository"} creation is forbidden for roles: ${roles}`
      );
    }
    // @ts-ignore
    return await this.service.create({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => GitHubRepository)
  @nestAccessControl.UseRoles({
    resource: "GitHubRepository",
    action: "update",
    possession: "any",
  })
  async updateGitHubRepository(
    @graphql.Args() args: UpdateGitHubRepositoryArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<GitHubRepository | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "update",
      possession: "any",
      resource: "GitHubRepository",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"GitHubRepository"} update is forbidden for roles: ${roles}`
      );
    }
    try {
      // @ts-ignore
      return await this.service.update({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => GitHubRepository)
  @nestAccessControl.UseRoles({
    resource: "GitHubRepository",
    action: "delete",
    possession: "any",
  })
  async deleteGitHubRepository(
    @graphql.Args() args: DeleteGitHubRepositoryArgs
  ): Promise<GitHubRepository | null> {
    try {
      // @ts-ignore
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
