export enum BillingFeature {
  AwsCodeCommit = "feature-awscodecommit",
  Bitbucket = "feature-bitbucket",
  BlockBuild = "feature-block-build",
  BlockWorkspaceCreation = "feature-block-workspace-creation",
  BranchPerResource = "feature-branch-per-resource",
  ChangeGitBaseBranch = "feature-change-git-base-branch",
  CodeGenerationBuilds = "feature-code-generation-builds",
  CodeGeneratorVersion = "feature-code-generator-version",
  CodePushToGit = "feature-code-push-to-git",
  CustomActions = "feature-custom-actions",
  EntitiesPerService = "feature-entities-per-service",
  GitLab = "feature-gitlab",
  IgnoreValidationCodeGeneration = "feature-ignore-validation-code-generation",
  ImportDBSchema = "feature-import-db-schema",
  Notification = "feature-notifications",
  Projects = "feature-projects",
  RedesignArchitecture = "feature-redesign-architecture",
  Services = "feature-services",
  ServicesAboveEntitiesPerServiceLimit = "feature-services-above-entities-per-service-limit",
  ServicesWithManyEntities = "feature-services-wth-many-entities",
  SmartGitSync = "feature-smart-git-sync",
  TeamMembers = "feature-team-members",
}
