export const CODE_BUILD_PROJECT_NAME = 'CODE_BUILD_PROJECT_NAME';
export const CODE_BUILD_CG_BASE_LOCATION = 'CODE_BUILD_CG_BASE_LOCATION';
export const CODE_BUILD_INPUT_BASE_LOCATION = 'CODE_BUILD_INPUT_BASE_LOCATION';

export const GENERATE_RESOURCE_TOPIC = 'GENERATE_RESOURCE_TOPIC';
export const BUILD_STATUS_TOPIC = 'BUILD_STATUS_TOPIC';

export const BUILD_STATE_TOPIC = 'BUILD_STATE_TOPIC';
export const BUILD_PHASE_TOPIC = 'BUILD_PHASE_TOPIC';

export const BUILD_ARTIFACT_S3_BUCKET = 'BUILD_ARTIFACT_S3_BUCKET';
export const BUILD_ARTIFACT_S3_LOCATION = 'BUILD_ARTIFACT_S3_LOCATION';

export const BUILD_IMAGE_NAME = 'BUILD_IMAGE_NAME';
export const BUILD_IMAGE_VERSION = 'BUILD_IMAGE_VERSION';

export const GET_BUILD_BY_RUN_ID_TOPIC = 'GET_BUILD_BY_RUN_ID_TOPIC';
