export const CODE_BUILD_PROJECT_NAME = 'CODE_BUILD_PROJECT_NAME';
export const CODE_BUILD_CG_BASE_LOCATION = 'CODE_BUILD_CG_BASE_LOCATION';
export const CODE_BUILD_INPUT_BASE_LOCATION = 'CODE_BUILD_INPUT_BASE_LOCATION';

export const GENERATE_RESOURCE_TOPIC = 'GENERATE_RESOURCE_TOPIC';
export const BUILD_STATUS_TOPIC = 'BUILD_STATUS_TOPIC';
