export const CODE_BUILD_PROJECT_NAME = 'CODE_BUILD_PROJECT_NAME';
export const CODE_BUILD_CG_BASE_LOCATION = 'CODE_BUILD_CG_BASE_LOCATION';
export const CODE_BUILD_INPUT_BASE_LOCATION = 'CODE_BUILD_INPUT_BASE_LOCATION';
