export enum BillingFeature {
  Services = "feature-services",
  TeamMembers = "feature-team-members",
  EntitiesPerService = "feature-entities-per-service",
  ServicesWithManyEntities = "feature-services-wth-many-entities",
  CodeGenerationBuilds = "feature-code-generation-builds",
  CodePushToGit = "feature-code-push-to-git",
  IgnoreValidationCodeGeneration = "feature-ignore-validation-code-generation",
  HideNotifications = "feature-ignore-validation-code-generation-hide-notifications",
  AwsCodeCommit = "feature-awscodecommit",
  Bitbucket = "feature-bitbucket",
  ImportDBSchema = "feature-import-db-schema",
  ChangeGitBaseBranch = "feature-change-git-base-branch",
  Notification = "feature-notifications",
  CodeGeneratorVersion = "feature-code-generator-version",
  ShowCodeGeneratorVersion = "feature-show-dsg-versions",
}
