{{- define "amplication-client.ingress" -}}
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
{{- end }}
{{- if .Values.ingress.enabled }}
{{ include "base.ingress" (list . "amplication-client.ingress") -}}
{{- end }}


