export const BASE_BUILDS_FOLDER = 'BASE_BUILDS_FOLDER';
export const GENERATE_PULL_REQUEST_TOPIC = 'GENERATE_PULL_REQUEST_TOPIC';
export const CHECK_USER_ACCESS_TOPIC = 'CHECK_USER_ACCESS_TOPIC';
export const BUILD_STATUS_TOPIC = 'BUILD_STATUS_TOPIC';
