/* eslint-disable @typescript-eslint/naming-convention */
export class Env {
  static readonly CLIENT_HOST = "CLIENT_HOST";
  static readonly HOST = "HOST";

  static readonly BITBUCKET_CLIENT_ID = "BITBUCKET_CLIENT_ID";
  static readonly BITBUCKET_CLIENT_SECRET = "BITBUCKET_CLIENT_SECRET";

  static readonly GITLAB_CLIENT_ID = "GITLAB_CLIENT_ID";
  static readonly GITLAB_CLIENT_SECRET = "GITLAB_CLIENT_SECRET";

  static readonly GITHUB_APP_CLIENT_ID = "GITHUB_APP_CLIENT_ID";
  static readonly GITHUB_APP_CLIENT_SECRET = "GITHUB_APP_CLIENT_SECRET";
  static readonly GITHUB_APP_APP_ID = "GITHUB_APP_APP_ID";
  static readonly GITHUB_APP_INSTALLATION_URL = "GITHUB_APP_INSTALLATION_URL";
  static readonly GITHUB_APP_PRIVATE_KEY = "GITHUB_APP_PRIVATE_KEY";

  static readonly GITHUB_DEMO_REPO_ORGANIZATION_NAME =
    "GITHUB_DEMO_REPO_ORGANIZATION_NAME";
  static readonly GITHUB_DEMO_REPO_INSTALLATION_ID =
    "GITHUB_DEMO_REPO_INSTALLATION_ID";

  static readonly BILLING_ENABLED = "BILLING_ENABLED";
  static readonly BILLING_API_KEY = "BILLING_API_KEY";

  static readonly CONTACT_US_LINK = "CONTACT_US_LINK";

  static readonly STIGG_WEBHOOKS_SECRET = "STIGG_WEBHOOKS_SECRET";

  static readonly AUTH_ISSUER_BASE_URL = "AUTH_ISSUER_BASE_URL";
  static readonly AUTH_ISSUER_MANAGEMENT_BASE_URL =
    "AUTH_ISSUER_MANAGEMENT_BASE_URL";
  static readonly AUTH_ISSUER_CLIENT_ID = "AUTH_ISSUER_CLIENT_ID";
  static readonly AUTH_ISSUER_CLIENT_SECRET = "AUTH_ISSUER_CLIENT_SECRET";
  static readonly AUTH_ISSUER_CLIENT_DB_CONNECTION =
    "AUTH_ISSUER_CLIENT_DB_CONNECTION";
  static readonly AUTH_ISSUER_CLIENT_DB_CONNECTION_ID =
    "AUTH_ISSUER_CLIENT_DB_CONNECTION_ID";

  static readonly USER_LAST_ACTIVE_DAYS = "USER_LAST_ACTIVE_DAYS";
  static readonly CRON_SECRET_KEY = "CRON_SECRET_KEY";

  static readonly FEATURE_CUSTOM_ACTIONS_ENABLED =
    "FEATURE_CUSTOM_ACTIONS_ENABLED";

  static readonly CHAT_OPENAI_KEY = "CHAT_OPENAI_KEY";
  static readonly CHAT_ASSISTANT_ID = "CHAT_ASSISTANT_ID";
  static readonly FEATURE_AI_ASSISTANT_ENABLED = "FEATURE_AI_ASSISTANT_ENABLED";
  static readonly PLUGIN_API_URL = "PLUGIN_API_URL";

  static readonly AWS_MARKETPLACE_INTEGRATION_ACCOUNT_ID =
    "AWS_MARKETPLACE_INTEGRATION_ACCOUNT_ID";
  static readonly AWS_MARKETPLACE_INTEGRATION_KEY =
    "AWS_MARKETPLACE_INTEGRATION_KEY";
  static readonly AWS_MARKETPLACE_INTEGRATION_SECRET =
    "AWS_MARKETPLACE_INTEGRATION_SECRET";
}
