name: Docs Bug Report
description: Problems and issues with docs of Amplication
labels: ["type: bug", "type: docs"]
body:
  - type: markdown
    attributes:
      value: "
        <img src='https://avatars.githubusercontent.com/u/65107786?s=200&v=4' align='left' width='80' height='80'>
        Thank you for finding the time to report the problem!

        We appreciate the community's efforts to improve Amplication.

        Note, that after you create an issue, if you have a change ready to submit!

        You can open [Pull Request](https://github.com/amplication/amplication/pulls) immediately after.
        <br clear='left'/>"
  - type: textarea
    attributes:
      label: Describe the issue with documentation
      description: Please describe the issue with documentation you have.
      placeholder: >
        Please include links to the documentation that has the problem and possibly screenshots showing
        the problem. Explain why do you think it is an issue. Make sure you include view of the target
        audience of the documentation. Please explain why you think the docs are wrong.
    validations:
      required: true
  - type: textarea
    attributes:
      label: How to solve the problem
      description: How do you think the problem can be solved?
      placeholder: >
        Please explain how you think the documentation could be fixed. Ideally specify where a new or missing
        documentation should be added and what kind of information should be included. Sometimes people
        writing the documentation do not realise that some assumptions the have might not be in the heads
        of the reader, so try to explain exactly what you would like to see in the docs and why.
  - type: dropdown
    attributes:
      label: Are you willing to submit PR?
      description: >
        This is absolutely not required, but we are happy to guide you in the contribution process
        especially if you already have a good understanding of how to implement the fix.
        Amplication is a community-managed project and we love to bring new contributors in.
        Find us in #support on [Discord](https://amplication.com/discord)!
      multiple: true
      options:
        - "Yes I am willing to submit a PR!"
  - type: markdown
    attributes:
      value: <br>
  - type: markdown
    attributes:
      value: By submitting this issue I agree to follow this project`s [Code of Conduct](https://github.com/amplication/amplication/blob/master/CODE_OF_CONDUCT.md)