name: Feature Request
description: Submit a proposal for a new feature
labels: ["type: feature request"]
body:
  - type: markdown
    attributes:
      value: "
        <img src='https://avatars.githubusercontent.com/u/65107786?s=200&v=4' align='left' width='80' height='80'>
        Thank you for finding the time to propose new feature!

        We really appreciate the community efforts to improve Amplication.

        Note, that you do not need to create an issue if you have a change ready to submit!

        You can open [Pull Request](https://github.com/amplication/amplication/pulls) immediately instead.
        <br clear='left'/>"
  - type: textarea
    attributes:
      label: Feature description
      description: Describe your feature proposal
  - type: textarea
    attributes:
      label: Use case
      description: Describe what you are trying to achive
  - type: dropdown
    attributes:
      label: Are you willing to submit PR?
      description: >
        This is absolutely not required, but we are happy to guide you in the contribution process
        especially if you already have a good understanding of how to implement the fix.
        Amplication is a community-managed project and we love to bring new contributors in.
        Find us in #how-to-pr on [Discord](https://discord.gg/cEcS9zDA)!
      multiple: true
      options:
        - "Yes I am willing to submit a PR!"
  - type: dropdown
    attributes:
      label: Code of Conduct
      description: The [Code of Conduct](https://github.com/amplication/amplication/blob/master/code_of_conduct.md) helps create a safe space for everyone. We require
        that everyone agrees to it.
      multiple: true
      options:
        - "I agree to follow this project's Code of Conduct"
    validations:
      required: true
