export const HOST = "http://localhost:3000";
export const HOME_PAGE_URL = `${HOST}/`;
export const LOGIN_URL = `${HOST}/login`;
export const LOGIN_CONTINUE_BUTTON_CONTENT = "Continue";
export const A_SIGN_UP = "Sign up";
export const I_SIGN_OUT = "log_out_outline";
export const ADD_FIELD_BUTTON = "Add field";
export const ADD_DESCRIPTION_BUTTON = "Add description";
export const CLOSE_BUTTON = "close";
