export class Env {
  static readonly PORT = 'PORT';

  static readonly CREATE_PR_REQUEST_TOPIC = 'CREATE_PR_REQUEST_TOPIC';
  static readonly CREATE_PR_SUCCESS_TOPIC = 'CREATE_PR_SUCCESS_TOPIC';
  static readonly CREATE_PR_FAILURE_TOPIC = 'CREATE_PR_FAILURE_TOPIC';

  static readonly BUILD_ARTIFACTS_BASE_FOLDER = 'BUILD_ARTIFACTS_BASE_FOLDER';
  static readonly BUILD_ARTIFACTS_CODE_FOLDER = 'BUILD_ARTIFACTS_CODE_FOLDER';
}
