export const PRODUCER_KAFKA_KEY_SERIALIZER = "PRODUCER_KAFKA_KEY_SERIALIZER"
export const PRODUCER_KAFKA_VALUE_SERIALIZER = "PRODUCER_KAFKA_VALUE_SERIALIZER"

export const CONSUMER_KAFKA_KEY_SERIALIZER = "CONSUMER_KAFKA_KEY_SERIALIZER"
export const CONSUMER_KAFKA_VALUE_SERIALIZER = "CONSUMER_KAFKA_VALUE_SERIALIZER"

export interface Serializer<T>{
    serialize(value:T):string
    deserialize(value:Buffer | null):T
}