export const KAFKA_GROUP_ID = "KAFKA_GROUP_ID";
export const KAFKA_BROKERS = "KAFKA_BROKERS";
export const KAFKA_CLIENT_ID = "KAFKA_CLIENT_ID";
export const KAFKA_CLIENT_CONFIG_SSL = "KAFKA_CLIENT_CONFIG_SSL";
