export const KAFKA_GROUP_ID = "KAFKA_GROUP_ID";
export const KAFKA_BROKERS = "KAFKA_BROKERS";
export const KAFKA_CLIENT_ID = "KAFKA_CLIENT_ID";
export const KAFKA_CLIENT_CONFIG_SSL = "KAFKA_CLIENT_CONFIG_SSL";
export const KAFKA_CLIENT_CONSUMER_SESSION_TIMEOUT =
  "KAFKA_CLIENT_CONSUMER_SESSION_TIMEOUT";
export const KAFKA_CLIENT_CONSUMER_REBALANCE_TIMEOUT =
  "KAFKA_CLIENT_CONSUMER_REBALANCE_TIMEOUT";
export const KAFKA_CLIENT_CONSUMER_HEARTHBEAT =
  "KAFKA_CLIENT_CONSUMER_HEARTHBEAT";
