apiVersion: v1
kind: PersistentVolume
metadata:
  name: dsg-jobs-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0a5d600fe9ec1387f::fsap-0c0986f263735b48c