apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.global.pv.name }}
spec:
  capacity:
    storage: {{ .Values.global.pv.storageCapacity }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: efs.csi.aws.com
    volumeHandle: {{ .Values.global.pv.handle }}