/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { Public } from "../../decorators/public.decorator";
import { Generator } from "./Generator";
import { GeneratorFindManyArgs } from "./GeneratorFindManyArgs";
import { GeneratorFindUniqueArgs } from "./GeneratorFindUniqueArgs";
import { VersionFindManyArgs } from "../../version/base/VersionFindManyArgs";
import { Version } from "../../version/base/Version";
import { GeneratorService } from "../generator.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Generator)
export class GeneratorResolverBase {
  constructor(
    protected readonly service: GeneratorService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @Public()
  @graphql.Query(() => [Generator])
  async generators(
    @graphql.Args() args: GeneratorFindManyArgs
  ): Promise<Generator[]> {
    return this.service.generators(args);
  }

  @Public()
  @graphql.Query(() => Generator, { nullable: true })
  async generator(
    @graphql.Args() args: GeneratorFindUniqueArgs
  ): Promise<Generator | null> {
    const result = await this.service.generator(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @Public()
  @graphql.ResolveField(() => [Version], { name: "version" })
  async findVersion(
    @graphql.Parent() parent: Generator,
    @graphql.Args() args: VersionFindManyArgs
  ): Promise<Version[]> {
    const results = await this.service.findVersion(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }
}
