/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { GeneratorService } from "../generator.service";
import { Public } from "../../decorators/public.decorator";
import { GeneratorFindManyArgs } from "./GeneratorFindManyArgs";
import { Generator } from "./Generator";
import { GeneratorWhereUniqueInput } from "./GeneratorWhereUniqueInput";
import { VersionFindManyArgs } from "../../version/base/VersionFindManyArgs";
import { Version } from "../../version/base/Version";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class GeneratorControllerBase {
  constructor(
    protected readonly service: GeneratorService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @Public()
  @common.Get()
  @swagger.ApiOkResponse({ type: [Generator] })
  @ApiNestedQuery(GeneratorFindManyArgs)
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async generators(@common.Req() request: Request): Promise<Generator[]> {
    const args = plainToClass(GeneratorFindManyArgs, request.query);
    return this.service.generators({
      ...args,
      select: {
        createdAt: true,
        fullName: true,
        id: true,
        isActive: true,
        name: true,
        updatedAt: true,
      },
    });
  }

  @Public()
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Generator })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async generator(
    @common.Param() params: GeneratorWhereUniqueInput
  ): Promise<Generator | null> {
    const result = await this.service.generator({
      where: params,
      select: {
        createdAt: true,
        fullName: true,
        id: true,
        isActive: true,
        name: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @Public()
  @common.Get("/:id/version")
  @ApiNestedQuery(VersionFindManyArgs)
  async findVersion(
    @common.Req() request: Request,
    @common.Param() params: GeneratorWhereUniqueInput
  ): Promise<Version[]> {
    const query = plainToClass(VersionFindManyArgs, request.query);
    const results = await this.service.findVersion(params.id, {
      ...query,
      select: {
        changelog: true,
        createdAt: true,
        deletedAt: true,

        generator: {
          select: {
            id: true,
          },
        },

        id: true,
        isActive: true,
        isDeprecated: true,
        name: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }
}
