export class Env {
  static readonly PORT = 'PORT';

  static readonly CODE_GENERATION_REQUEST_TOPIC =
    'CODE_GENERATION_REQUEST_TOPIC';
  static readonly CODE_GENERATION_SUCCESS_TOPIC =
    'CODE_GENERATION_SUCCESS_TOPIC';
  static readonly CODE_GENERATION_FAILURE_TOPIC =
    'CODE_GENERATION_FAILURE_TOPIC';

  static readonly CREATE_PR_REQUEST_TOPIC = 'CREATE_PR_REQUEST_TOPIC';
  static readonly CREATE_PR_SUCCESS_TOPIC = 'CREATE_PR_SUCCESS_TOPIC';
  static readonly CREATE_PR_FAILURE_TOPIC = 'CREATE_PR_FAILURE_TOPIC';

  static readonly DSG_LOG_TOPIC = 'DSG_LOG_TOPIC';

  static readonly DSG_RUNNER_URL = 'DSG_RUNNER_URL';

  static readonly BASE_BUILDS_FOLDER = 'BASE_BUILDS_FOLDER';
  static readonly RESOURCE_DATA_FILE_NAME = 'RESOURCE_DATA_FILE_NAME';
}
