export const JWT_SECRET_KEY = "JWT_SECRET_KEY";

export const BUILD_ARTIFACTS_BASE_FOLDER = "BUILD_ARTIFACTS_BASE_FOLDER";
export const BUILD_ARTIFACTS_CODE_FOLDER = "BUILD_ARTIFACTS_CODE_FOLDER";

export const CHECK_USER_ACCESS_TOPIC = "CHECK_USER_ACCESS_TOPIC";
