export enum BuildStatusEnum {
  Init = 'INIT',
  InProgress = 'IN_PROGRESS',
  Failed = 'FAILED',
  Succeeded = 'SUCCEEDED',
  Succeed = 'SUCCEED',
  Submitted = 'SUBMITTED',
  Provisioning = 'PROVISIONING',
  DownloadSource = 'DOWNLOAD_SOURCE',
  Install = 'INSTALL',
  PreBuild = 'PRE_BUILD',
  Build = 'BUILD',
  PostBuild = 'POST_BUILD',
  UploadArtifacts = 'UPLOAD_ARTIFACTS',
  Finalizing = 'FINALIZING',
  TimedOut = 'TIMED_OUT',
  Stopped = 'STOPPED',
  Fault = 'FAULT',
  ClientError = 'CLIENT_ERROR',
  Ready = 'READY',
}
