{{ include "base.deployment" (list . "amplication-git-pull-service.deployment") -}}
{{- define "amplication-git-pull-service.deployment" -}}
spec:
  template:
    spec:
      initContainers:
        - name: "{{ .Values.name }}-migrate"
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          {{- if .Values.autoscaling.enabled }}
          resources:
            limits:
              cpu: {{ .Values.maxCPU }}
              memory: {{ .Values.minMemory }}
            requests:
              cpu: {{ .Values.minCPU }}
              memory: {{ .Values.maxMemory }}
          {{- end }}
          command: ["/bin/sh"]
          args: ["-c", "npm run migrate:up", ";", "exit"]
          env:
          - name: POSTGRESQL_URL
            valueFrom:
              secretKeyRef:
                name: {{ .Values.name }}
                key: POSTGRESQL_URL
                optional: false
{{- end }}