export const {
  NX_REACT_APP_GITHUB_AUTH_ENABLED: REACT_APP_GITHUB_AUTH_ENABLED,
  NX_REACT_APP_ANALYTICS_API_KEY: REACT_APP_ANALYTICS_API_KEY,
  NX_REACT_APP_ANALYTICS_API_DOMAIN: REACT_APP_ANALYTICS_API_DOMAIN,
  NX_REACT_APP_ANALYTICS_DOMAIN: REACT_APP_ANALYTICS_DOMAIN,
  NX_REACT_APP_FEATURE_FLAGS: REACT_APP_FEATURE_FLAGS,
  NX_REACT_APP_GITHUB_CONTROLLER_LOGIN_URL:
    REACT_APP_GITHUB_CONTROLLER_LOGIN_URL,
  NX_REACT_APP_STORAGE_GATEWAY_URL: REACT_APP_STORAGE_GATEWAY_URL,
  NX_REACT_APP_DATA_SOURCE: REACT_APP_DATA_SOURCE,
  NX_REACT_APP_PLUGIN_API_DATA_SOURCE: REACT_APP_PLUGIN_API_DATA_SOURCE,
  NX_REACT_APP_CODE_GENERATOR_CATALOG_API_DATA_SOURCE:
    REACT_APP_CODE_GENERATOR_CATALOG_API_DATA_SOURCE,
  NX_REACT_APP_PLUGIN_VERSION_USE_LATEST: REACT_APP_PLUGIN_VERSION_USE_LATEST,
  NX_REACT_APP_BILLING_ENABLED: REACT_APP_BILLING_ENABLED,
  NX_REACT_APP_BILLING_API_KEY: REACT_APP_BILLING_API_KEY,
  NX_REACT_APP_AUTH_LOGIN_URI: REACT_APP_AUTH_LOGIN_URI,
  NX_REACT_APP_AUTH_LOGOUT_URI: REACT_APP_AUTH_LOGOUT_URI,
  NX_REACT_APP_NOVU_IDENTIFIER: REACT_APP_NOVU_IDENTIFIER,
  NX_REACT_APP_RUM_APP_ID: REACT_APP_RUM_APP_ID,
  NX_REACT_APP_RUM_ROLE_ID: REACT_APP_RUM_ROLE_ID,
  NX_REACT_APP_RUM_POOL_ID: REACT_APP_RUM_POOL_ID,
} = process.env;
