name: amplication-git-push-webhook-service
    
replicaCount: 1
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80
image:
  pullPolicy: Always
  repository: 407256539111.dkr.ecr.us-east-1.amazonaws.com/amplication-git-push-webhook-service-dev
  tag: 0.0.1
  imagePullSecrets: []

podAnnotations:
  cluster-autoscaler.kubernetes.io/safe-to-evict: "false"

maxMemory: "2Gi"
minMemory: "2Gi"
maxCPU: 1
minCPU: 1

service:
  type: ClusterIP
  port: 
    target: 3000
  protocol: TCP

ingress:
  enabled: true
  hostname: https://webhook.amplication.com

postgres:
  install: false
  postgresqlUsername: postgres
  postgresPassword: postgres
  db: amplication
  fullnameOverride: postgresql
  postgresql:
    image: groundnuty/k8s-wait-for:v1.3
    imagePullPolicy: Always
    primary:
      podLabels: { name: "postgres" }
