import { FullEntity } from "../types";
import * as models from "../models";

const entities: FullEntity[] = [
  {
    id: "b73e3670-daf6-11ea-87d0-0242ac130003",
    name: "Customer",
    displayName: "Customer",
    pluralDisplayName: "Customers",
    createdAt: new Date(),
    updatedAt: new Date(),
    appId: "6233b158-a2d4-4c9f-a9e4-f024d543fe6b",
    fields: [
      {
        id: "b73e3670-daf6-11ea-87d0-0242ac130003",
        fieldPermanentId: "ckenzw8p8040104jntevzdw5f",
        name: "id",
        displayName: "Id",
        dataType: models.EnumDataType.Id,
        properties: {},
        required: true,
        searchable: false,
        description: "",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: "b73e3670-daf6-11ea-87d0-0242ac130003",
        fieldPermanentId: "ckenzw8p8040104jntevzdw5f",
        name: "createdAt",
        displayName: "Created At",
        dataType: models.EnumDataType.CreatedAt,
        properties: {},
        required: true,
        searchable: false,
        description: "",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: "b73e3670-daf6-11ea-87d0-0242ac130003",
        fieldPermanentId: "ckenzw8p8040104jntevzdw5f",
        name: "updatedAt",
        displayName: "Updated At",
        dataType: models.EnumDataType.UpdatedAt,
        properties: {},
        required: true,
        searchable: false,
        description: "",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: "b73e3670-daf6-11ea-87d0-0242ac130003",
        fieldPermanentId: "ckenzw8p8040104jntevzdw5f",
        name: "email",
        displayName: "Email",
        dataType: models.EnumDataType.Email,
        properties: {},
        required: true,
        searchable: false,
        description: "",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: "b73e3670-daf6-11ea-87d0-0242ac130003",
        fieldPermanentId: "ckenzw8p8040104jntevzdw5f",
        name: "firstName",
        displayName: "First Name",
        dataType: models.EnumDataType.SingleLineText,
        properties: {},
        required: true,
        searchable: false,
        description: "",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: "b73e3670-daf6-11ea-87d0-0242ac130003",
        fieldPermanentId: "ckenzw8p8040104jntevzdw5f",
        name: "lastName",
        displayName: "Last Name",
        dataType: models.EnumDataType.SingleLineText,
        properties: {},
        required: true,
        searchable: false,
        description: "",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ],
    permissions: [
      {
        id: "82414924-3ea2-426a-9481-78434acc96ae",
        action: models.EnumEntityAction.Create,
        permissionFields: [],
        permissionRoles: [],
        type: models.EnumEntityPermissionType.AllRoles,
      },
      {
        id: "83b0ba26-b0b1-4bfc-9943-4b16808e548e",
        action: models.EnumEntityAction.Delete,
        permissionFields: [],
        permissionRoles: [],
        type: models.EnumEntityPermissionType.AllRoles,
      },
      {
        id: "9b8b8013-d311-49cc-9bbb-ad261919ada5",
        action: models.EnumEntityAction.Search,
        permissionFields: [],
        permissionRoles: [],
        type: models.EnumEntityPermissionType.AllRoles,
      },
      {
        id: "6efe6bcd-fc55-407f-837b-546c5264d16c",
        action: models.EnumEntityAction.Update,
        permissionFields: [],
        permissionRoles: [],
        type: models.EnumEntityPermissionType.AllRoles,
      },
      {
        id: "6efe6bcd-fc55-407f-837b-546c5264d16c",
        action: models.EnumEntityAction.View,
        permissionFields: [],
        permissionRoles: [],
        type: models.EnumEntityPermissionType.AllRoles,
      },
    ],
  },
];

export default entities;
