export const environment = {
  production: true,
  NX_REACT_APP_GITHUB_AUTH_ENABLED: true,
  NX_REACT_APP_GITHUB_CLIENT_ID: "",
  NX_REACT_APP_GITHUB_CONTROLLER_LOGIN_URL: "",
  NX_REACT_APP_SERVER_URI: "",
  NX_REACT_APP_PLUGIN_API_DATA_SOURCE: "",
  NX_REACT_APP_DATA_SOURCE: "",
  NX_REACT_APP_STORAGE_GATEWAY_URL: "",
  NX_REACT_APP_BILLING_ENABLED: true,
  NX_REACT_APP_BILLING_API_KEY: "",
  NX_REACT_APP_AMPLITUDE_API_KEY: "",
};
