name: CI-Pipeline

on:
  workflow_dispatch
  # push:
  #   branches: [master]
  # pull_request:
  #   branches: [master]
  #   types: [opened, reopened]

jobs:       
  changes:
    runs-on: ubuntu-latest
    outputs:
      services: ${{ steps.filter.outputs.array }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v17.3
        with:
          separator: ","
          files_ignore: |
            .github/**
          files: |
            packages/**

      - name: Filter array
        id: filter
        env:
          ARRAY: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          if [[ ! -z $ARRAY ]]
          then 
            echo "$ARRAY"
            final=''
            for string in $(echo $ARRAY | sed "s/,/ /g")
            do
              prefix="packages/"
              no_prefix=${string#"$prefix"}
              final+="\"$( cut -d '/' -f 1 <<< "$no_prefix" )\", "
            done
            final+=''
            mod=$(echo $final | tr ' ' '\n' | sort | uniq | tr '\n' ' ' | sed -e 's/[[:space:]]*$//')
            modi=${mod%?}
            modif=[$(echo "$modi")]
            echo $modif
            echo "::set-output name=array::$modif"
          else
            final=''
            for d in packages/*
            do
              prefix="packages/"
              no_prefix=${d#"$prefix"}
              final+="\"$( cut -d '/' -f 1 <<< "$no_prefix" )\", "
            done
            mod=$(echo $final | tr ' ' '\n' | sort | uniq | tr '\n' ' ' | sed -e 's/[[:space:]]*$//')
            modi=${mod%?}
            modif=[$(echo "$modi")]
            echo $modif
            echo "::set-output name=array::$modif"
          fi
  
  # format:
  #   runs-on: ubuntu-latest
  #   needs: changes
  #   if: ${{ needs.changes.outputs.services != '[]' && needs.changes.outputs.services != '' }}
  #   strategy:
  #     matrix:
  #       node-version: [16.x]
  #       service: ${{ fromJSON(needs.changes.outputs.services) }} 

  #   steps:
  #   - name: Checkout repository
  #     uses: actions/checkout@v2

  #   - name: Check docker-service
  #     id: check-docker-service
  #     env: 
  #       SERVICE: ${{ matrix.service }}
  #     run: |
  #       FILE=packages/$SERVICE/Dockerfile
  #       if [[ -f "$FILE" ]] 
  #       then
  #         echo "$FILE exists."
  #         echo "::set-output name=docker-service::true"
  #       else
  #         echo "::set-output name=docker-service::false"
  #       fi

  #   - name: Use Node.js ${{ matrix.node-version }}
  #     uses: actions/setup-node@v2
  #     with:
  #       node-version: ${{ matrix.node-version }}
  #       cache: 'npm'
        
  #   - name: "Install dependencies ${{ matrix.service }}"
  #     if: ${{ steps.check-docker-service.outputs.docker-service == 'true' }}
  #     run: npm ci

  #   - name: "Check format: ${{ matrix.service }}"
  #     if: ${{ steps.check-docker-service.outputs.docker-service == 'true' }}
  #     working-directory: packages/${{ matrix.service }}
  #     run: npm run check-format
      
  # lint:
  #   runs-on: ubuntu-latest
  #   needs: [changes]
  #   if: ${{ needs.changes.outputs.services != '[]' && needs.changes.outputs.services != '' }}
  #   strategy:
  #     matrix:
  #       node-version: [16.x]
  #       service: ${{ fromJSON(needs.changes.outputs.services) }} 

  #   steps:
  #   - name: Checkout repository
  #     uses: actions/checkout@v2

  #   - name: Check docker-service
  #     id: check-docker-service
  #     env: 
  #       SERVICE: ${{ matrix.service }}
  #     run: |
  #       FILE=packages/$SERVICE/Dockerfile
  #       if [[ -f "$FILE" ]] 
  #       then
  #         echo "$FILE exists."
  #         echo "::set-output name=docker-service::true"
  #       else
  #         echo "::set-output name=docker-service::false"
  #       fi

  #   - name: Use Node.js ${{ matrix.node-version }}
  #     uses: actions/setup-node@v2
  #     with:
  #       node-version: ${{ matrix.node-version }}
  #       cache: 'npm'
        
  #   - name: "Install dependencies ${{ matrix.service }}"
  #     if: ${{ steps.check-docker-service.outputs.docker-service == 'true' }}
  #     run: npm ci
        
  #   - name: "Lint first run: ${{ matrix.service }}"
  #     if: ${{ steps.check-docker-service.outputs.docker-service == 'true' }}
  #     working-directory: packages/${{ matrix.service }}
  #     run: npm run lint

  # build:
  #   runs-on: ubuntu-latest
  #   needs: [changes]
  #   if: ${{ needs.changes.outputs.services != '[]' && needs.changes.outputs.services != '' }}
  #   strategy:
  #     matrix:
  #       node-version: [16.x]
  #       service: ${{ fromJSON(needs.changes.outputs.services) }} 

  #   steps:
  #   - name: Checkout repository
  #     uses: actions/checkout@v2

  #   - name: Check docker-service
  #     id: check-docker-service
  #     env: 
  #       SERVICE: ${{ matrix.service }}
  #     run: |
  #       FILE=packages/$SERVICE/Dockerfile
  #       if [[ -f "$FILE" ]] 
  #       then
  #         echo "$FILE exists."
  #         echo "::set-output name=docker-service::true"
  #       else
  #         echo "::set-output name=docker-service::false"
  #       fi

  #   - name: Use Node.js ${{ matrix.node-version }}
  #     uses: actions/setup-node@v2
  #     with:
  #       node-version: ${{ matrix.node-version }}
  #       cache: 'npm'
        
  #   - name: "Install dependencies ${{ matrix.service }}"
  #     if: ${{ steps.check-docker-service.outputs.docker-service == 'true' }}
  #     run: npm ci

  #   - name: "Build packages first run: ${{ matrix.service }}"
  #     if: ${{ steps.check-docker-service.outputs.docker-service == 'true' }}
  #     working-directory: packages/${{ matrix.service }}
  #     run: npm run build
 
  # test:
  #   runs-on: ubuntu-latest
  #   needs: [changes]
  #   if: ${{ needs.changes.outputs.services != '[]' && needs.changes.outputs.services != '' }}
  #   strategy:
  #     matrix:
  #       node-version: [16.x]
  #       service: ${{ fromJSON(needs.changes.outputs.services) }} 

  #   steps:
  #   - name: Checkout repository
  #     uses: actions/checkout@v2

  #   - name: Check docker-service
  #     id: check-docker-service
  #     env: 
  #       SERVICE: ${{ matrix.service }}
  #     run: |
  #       FILE=packages/$SERVICE/Dockerfile
  #       if [[ -f "$FILE" ]] 
  #       then
  #         echo "$FILE exists."
  #         echo "::set-output name=docker-service::true"
  #       else
  #         echo "::set-output name=docker-service::false"
  #       fi

  #   - name: Use Node.js ${{ matrix.node-version }}
  #     uses: actions/setup-node@v2
  #     with:
  #       node-version: ${{ matrix.node-version }}
  #       cache: 'npm'
        
  #   - name: "Install dependencies ${{ matrix.service }}"
  #     if: ${{ steps.check-docker-service.outputs.docker-service == 'true' }}
  #     run: npm ci
    
  #   - name: "Test first run: ${{ matrix.service }}"
  #     if: ${{ steps.check-docker-service.outputs.docker-service == 'true' }}
  #     working-directory: packages/${{ matrix.service }}
  #     run: npm test

  docker:
    name: docker
    needs: [changes]
    if: always() && success() && (github.event_name == 'push')
    runs-on: ubuntu-latest
    outputs:
      docker-services: ${{ steps.check-docker-service.outputs.docker-service }}
    strategy:
      matrix:
        node-version: [16.x]
        service: ${{ fromJSON(needs.changes.outputs.services) }} 

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Check docker-service
        id: check-docker-service
        env: 
          SERVICE: ${{ matrix.service }}
        run: |
          FILE=packages/$SERVICE/Dockerfile
          if [[ -f "$FILE" ]] 
          then
            echo "$FILE exists."
            echo "::set-output name=docker-service::true"
          else
            echo "::set-output name=docker-service::false"
          fi
      
      - name: Set up Docker Buildx
        if: ${{ steps.check-docker-service.outputs.docker-service == 'true' }}
        uses: docker/setup-buildx-action@v1
            
      - name: Configure AWS credentials
        if: ${{ steps.check-docker-service.outputs.docker-service == 'true' }}
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 
          aws-region: us-east-1
          
      - name: Login to Amazon ECR
        id: login-ecr
        if: ${{ steps.check-docker-service.outputs.docker-service == 'true' }}
        uses: aws-actions/amazon-ecr-login@v1

      - name: Set hash
        if: ${{ steps.check-docker-service.outputs.docker-service == 'true' }}
        env:
          working-directory: packages/${{ matrix.service }}/Dockerfile
        run: |
          GITHUB_HASH_MOD=$(sha1sum packages/${{ matrix.service }}/Dockerfile | sha1sum)
          echo "GITHUB_HASH=${GITHUB_HASH_MOD%???}" >> $GITHUB_ENV
       
      - name: Check if repo exist
        working-directory: packages/${{ matrix.service }}
        if: ${{ steps.check-docker-service.outputs.docker-service == 'true' }}
        env: 
          ECR_REPOSITORY_STAGING: ${{ matrix.service }}-staging
          ECR_REPOSITORY_PROD: ${{ matrix.service }}-prod
        run: |
          if [[ $GITHUB_REF != 'refs/heads/master' ]]
          then 
            aws ecr describe-repositories --repository-names $ECR_REPOSITORY_STAGING || aws ecr create-repository --repository-name $ECR_REPOSITORY_STAGING
          else
            aws ecr describe-repositories --repository-names $ECR_REPOSITORY_PROD || aws ecr create-repository --repository-name $ECR_REPOSITORY_PROD
          fi

      - name: Check if tag already exist
        id: tag-exist
        if: ${{ steps.check-docker-service.outputs.docker-service == 'true' }}
        env: 
          ECR_REPOSITORY_STAGING: ${{ matrix.service }}-staging
          ECR_REPOSITORY_PROD: ${{ matrix.service }}-prod
        run: |
          set +e
          if [[ $GITHUB_REF != 'refs/heads/master' ]]
          then 
            cmd="$(aws ecr describe-images --repository-name=$ECR_REPOSITORY_STAGING --image-ids=imageTag=$GITHUB_HASH)"
          else
            cmd="$(aws ecr describe-images --repository-name=$ECR_REPOSITORY_PROD --image-ids=imageTag=$GITHUB_HASH)"
          fi
          if [[ ! -z "$cmd" ]]
          then  
            echo "tag already exist"
            echo "::set-output name=tag_exist::true"
          else
            echo "tag doesn't exist"
            echo "::set-output name=tag_exist::false"
          fi
      
      - name: set branch-name
        if: ${{ steps.check-docker-service.outputs.docker-service == 'true' }}
        run: |
          if [[ $GITHUB_REF != 'refs/heads/master' ]]
          then 
            echo "BRANCH_NAME=$(echo $GITHUB_REF_NAME | sed "s/\//-/g")" >> $GITHUB_ENV
          fi

      - name: Build, tag, and push image to Amazon ECR
        if: ${{ steps.check-docker-service.outputs.docker-service == 'true' && steps.tag-exist.outputs.tag_exist == 'false' }}
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY_STAGING: ${{ matrix.service }}-staging
          ECR_REPOSITORY_PROD: ${{ matrix.service }}-prod
        run: |
          if [[ $GITHUB_REF != 'refs/heads/master' ]]
          then 
            docker build -f ./packages/${{ matrix.service }}/Dockerfile . -t $ECR_REGISTRY/$ECR_REPOSITORY_STAGING:$GITHUB_HASH
            docker push $ECR_REGISTRY/$ECR_REPOSITORY_STAGING:$GITHUB_HASH
            MANIFEST=$(aws ecr batch-get-image --repository-name $ECR_REPOSITORY_STAGING --image-ids imageTag=$GITHUB_HASH --output json | jq --raw-output --join-output '.images[0].imageManifest')
            aws ecr put-image --repository-name $ECR_REPOSITORY_STAGING --image-tag ${{ github.sha }} --image-manifest "$MANIFEST"
            aws ecr put-image --repository-name $ECR_REPOSITORY_STAGING --image-tag ${{ env.BRANCH_NAME }} --image-manifest "$MANIFEST"
            aws ecr put-image --repository-name $ECR_REPOSITORY_STAGING --image-tag ${{ github.run_id }} --image-manifest "$MANIFEST"
          else 
            docker build -f ./packages/${{ matrix.service }}/Dockerfile . -t $ECR_REGISTRY/$ECR_REPOSITORY_PROD:$GITHUB_HASH
            docker push $ECR_REGISTRY/$ECR_REPOSITORY_PROD:$GITHUB_HASH
            MANIFEST=$(aws ecr batch-get-image --repository-name $ECR_REPOSITORY_PROD --image-ids imageTag=$GITHUB_HASH --output json | jq --raw-output --join-output '.images[0].imageManifest')
            aws ecr put-image --repository-name $ECR_REPOSITORY_PROD --image-tag ${{ github.sha }} --image-manifest "$MANIFEST"
            aws ecr put-image --repository-name $ECR_REPOSITORY_PROD --image-tag ${{ github.ref_name }} --image-manifest "$MANIFEST"
            aws ecr put-image --repository-name $ECR_REPOSITORY_PROD --image-tag ${{ github.run_id }} --image-manifest "$MANIFEST"
          fi

  service-chart:
    runs-on: ubuntu-latest
    needs: [docker,changes]
    if: ${{ needs.docker.outputs.docker-services == 'true' }}
    env:
      BUCKET_NAME: amplication-charts
      REGION: us-east-1
      SERVICE_CHART_PATH: amplication-charts/charts/services
    strategy:
      matrix:
        service: ${{ fromJSON(needs.changes.outputs.services) }} 
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }} 
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 
          aws-region: ${{ env.REGION }}

      - name: Check service folder exist
        id: check_folder
        run: |
          set +e
          server_folder=$(aws s3 ls "s3://$BUCKET_NAME/${{ matrix.service }}")
          if [[ -z "$server_folder" ]]
          then
            echo "No such folder in bucket"
            echo "::set-output name=create_folder::true"
          else
            echo "folder exist in bucket"
            echo "::set-output name=create_folder::false"
          fi

      - name: Update dependencies for service chart
        working-directory: ${{ env.SERVICE_CHART_PATH }}/${{ matrix.service }}
        run: |
          helm dependency update

      - name: Helm Template
        working-directory: ${{ env.SERVICE_CHART_PATH }}/${{ matrix.service }}
        id: helm-template
        run: |
          helm template amplication . > helm.log
      
      - env:
          TEMPLATES: "helm template\n${{ steps.helm-template.outputs.stdout }}"
        run: echo ${TEMPLATES}

      - name: Set hash
        env:
          working-directory: ${{ env.SERVICE_CHART_PATH }}/${{ matrix.service }}
        run: |
          GITHUB_HASH_MOD=$(sha1sum $working-directory | sha1sum)
          echo "GITHUB_HASH=${GITHUB_HASH_MOD%???}" >> $GITHUB_ENV

      - name: Upload artifact to s3
        working-directory: ${{ env.SERVICE_CHART_PATH }}
        run: |
          set +e
          if [[ ${{ steps.check_folder.outputs.create_folder == 'true' }} ]]
          then
            pwd
            tar -cvzf ${{ matrix.service }}_$GITHUB_HASH.tgz ./${{ matrix.service }}
            ls -l
            aws s3 cp ${{ matrix.service }}_$GITHUB_HASH.tgz s3://$BUCKET_NAME/${{ matrix.service }}/${{ matrix.service }}_$GITHUB_HASH.tgz
          else
            pwd
            tar -cvzf ${{ matrix.service }}_$GITHUB_HASH.tgz ./${{ matrix.service }}
            ls -l
            isTagExist=$(aws s3 ls s3://BUCKET-NAME/${{ matrix.service }} --recursive | grep ${{ matrix.service }}_$GITHUB_HASH.tgz)
            if [[ ! -z  "$isTagExist" ]]
            then 
              aws s3 cp ${{ matrix.service }}_$GITHUB_HASH.tgz s3://$BUCKET_NAME/${{ matrix.service }}/${{ matrix.service }}_$GITHUB_HASH.tgz
            fi
          fi

  umbrella-chart:
    needs: service-chart
    if: ${{ needs.docker.outputs.docker-services == 'true' }}
    env:
      BUCKET_NAME: amplication-charts
      REGION: us-east-1
      AMPLICATION_CHART_PATH: amplication-charts/charts/amplication
      SERVICE_CHART_PATH: amplication-charts/charts/services

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }} 
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 
          aws-region: ${{ env.REGION }}
      
      - name: Check amplication folder exist
        id: check_folder
        env:
          last_artifact: ${{ steps.last_artifact.outputs.service_artifact }}
        run: |
          set +e
          amplication_folder=$(aws s3 ls "s3://$BUCKET_NAME/amplication")
          if [[ -z "$amplication_folder" ]]
          then
            echo "No such folder in bucket"
            echo "::set-output name=create_folder::true"
          else
            echo "folder exist in bucket"
            echo "::set-output name=create_folder::false"
          fi

      - name: Helm Update Dependencies for umbrella-chart
        working-directory: ${{ env.AMPLICATION_CHART_PATH }}
        run: |
          helm dependency update

      - name: Helm Template
        working-directory: ${{ env.AMPLICATION_CHART_PATH }}
        id: helm-template
        run: |
          helm template amplication . > helm.log
      
      - env:
          TEMPLATES: "helm template\n${{ steps.helm-template.outputs.stdout }}"
        run: echo ${TEMPLATES}
      
      - name: Upload artifact to s3
        working-directory: ${{ env.AMPLICATION_CHART_PATH }}
        env:
          last_artifact: ${{ steps.last_artifact.outputs.amplication_artifact }}
        run: |
          set +e
          if [[ ${{ steps.check_folder.outputs.create_folder == 'true' }} ]]
          then
            pwd
            tar -cvzf amplication_$GITHUB_RUN_ID.tgz ./
            ls -l
            aws s3 cp amplication_$GITHUB_RUN_ID.tgz s3://$BUCKET_NAME/amplication_/amplication__$GITHUB_RUN_ID.tgz
          else
            pwd
            tar -cvzf amplication_$GITHUB_RUN_ID.tgz ./
            ls -l
            isTagExist=$(aws s3 ls s3://BUCKET-NAME/amplication_ --recursive | grep amplication__$GITHUB_RUN_ID.tgz)
            if [[ ! -z  "$isTagExist" ]]
            then 
              aws s3 cp amplication_$GITHUB_RUN_ID.tgz s3://$BUCKET_NAME/amplication_/amplication__$GITHUB_RUN_ID.tgz
            fi
          fi






 
      


      



