name: Reusable CI template

on:
  workflow_call:
    inputs:
      nx-head:
        type: string
        description: Commit SHA, branch or tag name used by Nx as git HEAD to calculate affected projects jobs. 
        required: true
      nx-base:
        type: string
        description: Commit SHA, branch or tag name used by Nx as git base to calculate affected projects jobs. 
        required: true
        default: next
      nx-skip-cache:
        type: boolean
        description: Rerun the tasks even when the results are available in the cache. 
        default: false
      nx-all:
        type: boolean
        description: Force Nx to consider all projects (apps and libs) as affected.
        default: false
    secrets:
      nx-cloud-token:
        required: true
    outputs:
      affected-projects:
        description: Nx projects affected by the change.
        value: ${{ jobs.ci.outputs.affected }}

env:
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.nx-cloud-token }}
  NX_BRANCH: ${{ inputs.nx-head }}
  NX_FORCE_ALL: ${{ fromJSON('["", "--all"]')[ inputs.nx-all ] }}  # This relies on type coercion, an implicit cast from boolean true to 1 or false to 0, which is then used as array index.
  NX_SKIP_NX_CACHE: ${{ inputs.nx-skip-cache }}
  BASE: ${{ inputs.nx-base }}

jobs:
  ci:
    name: Continuous Integration
    runs-on: ubuntu-20.04
    outputs:
      affected: ${{ steps.set-affected.outputs.affected }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: nrwl/nx-set-shas@v3
        with:
          main-branch-name: ${{ github.env.BASE }}

      - uses: actions/setup-node@v3
        with:
          node-version-file: 'package.json'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      
      - name: Cache global node modules
        id: cache-node-modules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }}

      - name: Cache other node modules
        id: cache-other-node-modules
        uses: actions/cache@v3
        env:
          cache-name: cache-other-node-modules
        with:
          path: |
            libs/data-service-generator/node_modules
            libs/util/code-gen-utils/node_modules
            packages/amplication-cli/node_modules
          key:  ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('./**/package-lock.json') }}

      - name: Install Dependencies
        if: ${{ steps.cache-node-modules.outputs.cache-hit != 'true' || steps.cache-other-node-modules.outputs.cache-hit != 'true' }}
        run: npm ci

      - name: Nx Workspace Lint
        run: npx nx workspace-lint

      - name: Nx Format Check
        run: npm run format:check $NX_FORCE_ALL

      - name: Lint
        run: npx nx affected --target=lint --parallel=3 $NX_FORCE_ALL

      - name: Test
        run: npx nx affected --target=test --parallel=3 $NX_FORCE_ALL

      - name: Build
        run: |
          npx nx affected --target=build --parallel=3 $NX_FORCE_ALL
          npx nx affected --target=postbuild --parallel=3 $NX_FORCE_ALL

      - name: Set Affected
        id: set-affected
        run: |
          export AFFECTED_PROJECTS=$(npx nx print-affected --type=app $NX_FORCE_ALL | jq -c .projects)
          echo affected projects: $AFFECTED_PROJECTS
          echo affected=$AFFECTED_PROJECTS >> $GITHUB_OUTPUT