name: Pull Request Labeler
# This workflows works in conjunction with the release.production.yml workflow to automate release notes based on labels.

on:
  pull_request_target:

env:
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}

jobs:
  nx:
    name: Nx
    uses: ./.github/workflows/nx.template.yml
    with:
      nx-head: ${{ github.event.pull_request.merge_commit_sha || "refs/pull/${{ github.event.number }}/merge" }}
      nx-base: ${{ github.sha }}

  triage-libs:
    name: Triage libs changes
    needs: nx
    if: ${{ needs.nx.outputs.affected-lib != '[]' && needs.nx.outputs.affected-lib != ''}}
    strategy:
      max-parallel: 1
      matrix:
        project: ${{ fromJson(needs.nx.outputs.affected-lib) }}
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Generate label configuration
        id: labeler-config
        run: |
          FILENAME=${{ matrix.project }}-labeler.yml
          echo "lib:${{ matrix.project }}:
                  pattern:
                    - '**'
                  color: '#CDD3DE'" > $FILENAME
          echo "config-file=$FILENAME" >> $GITHUB_OUTPUT
      - uses: overbit/labeler@main
        with:
          configuration-path: ${{ steps.labeler-config.outputs.config-file }}
          dot: true

  triage-apps:
    name: Triage app changes
    needs: [nx, triage-libs]
    if: ${{ always() && needs.nx.outputs.affected-apps != '[]' && needs.nx.outputs.affected-apps != '' }}
    strategy:
      max-parallel: 1
      matrix:
        project: ${{ fromJson(needs.nx.outputs.affected-apps) }}
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Generate label configuration
        id: labeler-config
        run: |
          LABEL_COLOR='#5319E7'
          APP_NAME=$(echo ${{ matrix.project }} | sed -e "s/^amplication-//")
          if [[ $APP_NAME == 'data-service-generator' ]]; then
            LABEL_COLOR='#B60205'
          fi

          FILENAME=${APP_NAME}-labeler.yml
          echo "app:${APP_NAME}:
                  pattern:
                    - '**'
                  color: ${LABEL_COLOR}" > $FILENAME
          echo "config-file=$FILENAME" >> $GITHUB_OUTPUT
      - uses: overbit/labeler@main
        with:
          configuration-path: ${{ steps.labeler-config.outputs.config-file }}
          dot: true

  triage-branch-sync-prs:
    name: Triage PR for branches sync
    if: ( github.head_ref == 'master' && github.base_ref == 'next' ) || ( github.head_ref == 'next' && github.base_ref == 'master' )
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Generate label configuration
        id: labeler-config
        run: |
          FILENAME=branch-sync-labeler.yml
          echo "ignore-from-release-notes:
                  pattern:
                    - '**'
                  color: '#000000'" > $FILENAME
          echo "config-file=$FILENAME" >> $GITHUB_OUTPUT
      - uses: overbit/labeler@main
        with:
          configuration-path: ${{ steps.labeler-config.outputs.config-file }}
          dot: true
