name: Validate Push

on:
  workflow_dispatch:
  pull_request:
      
jobs:
  lerna:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - run: npm i -g npm@7.3.0
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: |
            ~/.npm
            node_modules
            */*/node_modules
          key: pr-wf-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
              pr-wf-${{ runner.os }}-
      - name: npm ci
        run: npm ci --cache ~/.npm --prefer-offline --only=production --silent
      - name: Lerna Bootstrap
        run: npm run bootstrap
      - name: Lerna SINCE environment 
        run: echo "SINCE=origin/$GITHUB_BASE_REF" >> $GITHUB_ENV
      - name: Lerna Changed
        run: npx lerna changed --json

